[project]
dependencies = [
]                              
name = "coderag-bench"
requires-python = ">= 3.11"
scripts = { main = "coderag_bench:main" }
version = "0.1.0"

[build-system] 
build-backend = "hatchling.build"
requires = ["hatchling"]